# Use postgres/example user/password credentials
version: "3.7"

networks:
  bacchus-network:
    driver: bridge


services:
  web:
    restart: always
    build: 
      context: ./web
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./web
        target: /usr/src/app
    ports:
      - 5000:5000
    expose:
      - 5000
    networks:
      - bacchus-network
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
    command: ["python", "app.py"]